### ISSUE TITLE
ARM issue tracker

### ISSUE THREAD

**Issue by Tobias-Fischer** [RoboStack/ros-noetic#4]
- [x] qt (required for lots of stuff): https://github.com/conda-forge/qt-feedstock/pull/166
- [x] mono (required for OGRE): https://github.com/conda-forge/mono-feedstock/pull/19
- [x] OGRE (needs mono first)
- [x] opencv (https://github.com/conda-forge/opencv-feedstock/pull/243)
- [x] get cluster access: https://github.com/WorksOnArm/cluster/issues/220

@wolfv: Please complete the list
